name: "🐞 Bug Report"
description: "버그 제보"
title: "[FIX] "
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: "어떤 에러인지 설명해주세요. (예: 구체적으로 어떤 상황에서 발생하는지)"
      placeholder: "옆에 [BE or FE] 라벨도 꼭 달아주세요!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: "할 일을 체크박스 형태로 작성해주세요."
      placeholder: "-[] (...)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 참고 자료
      description: "참고 자료가 있다면 작성해 주세요."